FROM debian:sid
RUN apt-get update
RUN apt-get install -y apache2
COPY ./GCΤF{ΤHIS_IS_A_LOΟΟOOOOОOOΟOOOΟOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOG_FLAG}.html /var/www/html/.
EXPOSE 80
RUN service apache2 start
CMD apachectl -D FOREGROUND